### ISSUE TITLE
Isn't working?

### ISSUE THREAD

**Issue by aaron-navigator** [d0t1q/Play-Music-Grabber#1]
This isn't working for me.

    arod@partyposter:~$ python grabber.py
    arod@partyposter:~$

As you can see.  Nothing happens.  Are the musics being download somewhere but there is just no output?

**Comment by d0t1q** [comment]
Grabber.py is currently in pre-production (Version 0.0.0), and this repo only acts as a place holder.  I appreciate your interesting in my project, I will update you once I start.

Thanks
